language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23

sudo: false

jdk:
    - oraclejdk8

env:
  global:
    MALLOC_ARENA_MAX=2
    GRADLE_OPTS=-Xmx2048m -Dorg.gradle.parallel=false

addons:
  apt:
    packages:
      - tar
      - gzip
      - patch

before_install:
  - openssl aes-256-cbc -K $encrypted_20a9e8c66faa_key -iv $encrypted_20a9e8c66faa_iv -in travis/configs/mirror_private_config.tar.gz.enc -out travis/configs/mirror_private_config.tar.gz -d

install:
  # Extracts build configs into source tree
  - tar zxf travis/configs/mirror_private_config.tar.gz

before_script:
    - chmod +x gradlew

script: ./gradlew build --no-daemon --stacktrace