language: android
jdk:
    - oraclejdk8
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23
  licenses:
    - 'android-sdk-license-.+'

sudo: false

before_script:
    - chmod +x gradlew

script: "./gradlew build"