language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-21
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/